name: ranking_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  shared_preferences: ^2.0.5
  sqflite: ^2.0.0+3
  animate_do: ^2.0.0
  flutter_signature_pad: ^3.0.0
  searchable_dropdown: ^1.1.3
  grouped_buttons: ^1.0.4
  flutter_launcher_icons: ^0.9.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  multi_select_flutter: ^4.0.0
  multiselect: ^0.0.4
  flutter_progress_hud: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/hcg-icon.png"
  adaptive_icon_background: "assets/icon/hcg-icon.png"
flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/icon/